Page({
  data: {
      // tab切换 
      currentTab: 0,
      allList:[
        {
          image_src:'/images/q7.jpg',
          data:"棠棠者华绿意春夏马面",
          price:"198.00"
        },     
        {
          image_src:'/images/q6.jpg',
          data:"国风立领斜襟盘扣亮片绣花蕾丝鱼尾旗袍裙",
          price:"239.00"
        },
        {
          image_src:'/images/q12.jpg',
          data:"秋意银杏黄色套装",
          price:"676.00"
        },
        {
          image_src:'/images/q1.jpg',
          data:"春花秋月-海棠罗长衫搭配堆金领抹",
          price:"239.00"
        },
        {
          image_src:'/images/q2.jpg',
          data:"原创明制立领竖领翻领对襟套装",
          price:"560.00"
        },
        {
          image_src:'/images/q3.jpg',
          data:"蜜桃乌龙宋制百褶裙",
          price:"158.00"
        },
        {
          image_src:'/images/q8.jpg',
          data:"原创眼影盘系列-大雪套装",
          price:"339.00"
        },
        {
          image_src:'/images/q5.jpg',
          data:"柳黄真丝顺纡短衫",
          price:"289.00"
        },
        {
          image_src:'/images/q4.jpg',
          data:"栗仁燕麦秋冬明制圆领短袄",
          price:"239.00"
        },
        {
          image_src:'/images/q9.jpg',
          data:"原创春日来刺绣马面",
          price:"339.00"
        },
        {
          image_src:'/images/q10.jpg',
          data:"日常改良版宋制",
          price:"475.00"
        },
        {
          image_src:'/images/q11.jpg',
          data:"梅雪仿花罗日常汉服",
          price:"320.00"
        },  
        {
          image_src:'/images/q13.jpg',
          data:"基础款大众旗袍",
          price:"246.00"
        },
        {
          image_src:'/images/q14.jpg',
          data:"梅竹双清对襟衫",
          price:"244.00"
        },
        {
          image_src:'/images/q15.jpg',
          data:"暗花真伦纱衫与黄绿晕染顺行裙",
          price:"380.00"
        },
        {
          image_src:'/images/q16.jpg',
          data:"雾色栖青半身裙",
          price:"179.00"
        },
        {
          image_src:'/images/q17.jpg',
          data:"靛青色夏款马面裙",
          price:"380.00"
        },
        {
          image_src:'/images/q18.jpg',
          data:"以梦兰夏日马面",
          price:"240.00"
        },
        {
          image_src:'/images/q19.jpg',
          data:"明制竖领对襟衫琵琶",
          price:"238.00"
        },
        {
          image_src:'/images/q20.jpg',
          data:"珍珠白鸢尾与勿忘草半袖褂子",
          price:"439.00"
        },
        {
          image_src:'/images/q21.jpg',
          data:"细葛含风软一",
          price:"246.00"
        },
        {
          image_src:'/images/q22.jpg',
          data:"黛紫嫣红套装",
          price:"368.00"
        }
],
      zsList:[
        {
          image_src:'/images/q12.jpg',
          data:"眼影盘系列-秋意银杏黄套装",
          price:"576.00"
        },
        {
          image_src:'/images/q1.jpg',
          data:"芍药璎珞堆金领衫",
          price:"289.00"
        }, 
        {
          image_src:'/images/q9.jpg',
          data:"马面立领袄琵琶袖",
          price:"339.00"
        },         
        {
          image_src:'/images/q15.jpg',
          data:"茶花罗抹胸",
          price:"380.00"
        },
        {
          image_src:'/images/q16.jpg',
          data:"雾色栖青半身裙",
          price:"299.00"
        },
        {
          image_src:'/images/q18.jpg',
          data:"以梦兰夏日马面",
          price:"580.00"
        },
        {
          image_src:'/images/q19.jpg',
          data:"明制竖领对襟衫琵琶",
          price:"368.00"
        },
        {
          image_src:'/images/q20.jpg',
          data:"珍珠白鸢尾与勿忘草半袖褂子",
          price:"￥439.00"
        },
        {
          image_src:'/images/q21.jpg',
          data:"细葛含风软一",
          price:"246.00"
        },
        {
          image_src:'/images/q22.jpg',
          data:"黛紫嫣红套装",
          price:"368.00"
        }
],
      qzList:[
    {
      image_src:'/images/q12.jpg',
      data:"眼影盘系列-秋意银杏黄套装",
      price:"576.00"
    },
    {
      image_src:'/images/q8.jpg',
      data:"长袖旗袍盘扣贴身知性优雅连衣裙",
      price:"239.00"
    },
    {
      image_src:'/images/q5.jpg',
      data:"柳黄真丝顺纡短衫",
      price:"289.00"
    },
    {
      image_src:'/images/q14.jpg',
      data:"重工蕾丝旗袍中国风唯美绣花包臀裙",
      price:"244.00"
    },
    {
      image_src:'/images/q21.jpg',
      data:"细葛含风软一",
      price:"246.00"
    },
    {
      image_src:'/images/q15.jpg',
      data:"复古中国风旗袍桑蚕丝春季中袖气质",
      price:"380.00"
    },
    {
      image_src:'/images/q20.jpg',
      data:"珍珠白鸢尾与勿忘草半袖褂子",
      price:"439.00"
    }
],
      fgList:[
    {
      image_src:'/images/q4.jpg',
      data:"甜美小清新长袖旗袍老缎子少女复古裙",
      price:"239.00"
    },
    {
      image_src:'/images/q6.jpg',
      data:"国风立领斜襟盘扣亮片绣花蕾丝鱼尾旗袍裙",
      price:"239.00"
    },
    {
      image_src:'/images/q3.jpg',
      data:"蜜桃乌龙宋制百褶裙",
      price:"248.00"
    },
    {
      image_src:'/images/q5.jpg',
      data:"柳黄真丝顺纡短衫",
      price:"289.00"
    },
    {
      image_src:'/images/q7.jpg',
      data:"棠棠者华绿意春夏马面",
      price:"398.00"
    }, 
    {
      image_src:'/images/q9.jpg',
      data:"原创春日来刺绣马面",
      price:"339.00"
    },
    {
      image_src:'/images/q10.jpg',
      data:"日常改良版宋制",
      price:"475.00"
    },
    {
      image_src:'/images/q11.jpg',
      data:"梅雪仿花罗日常汉服",
      price:"320.00"
    },  
    {
      image_src:'/images/q13.jpg',
      data:"基础款大众旗袍",
      price:"246.00"
    },
    {
      image_src:'/images/q20.jpg',
      data:"珍珠白鸢尾与勿忘草半袖褂子",
      price:"439.00"
    }
],
      hyList:[
    {
      image_src:'/images/q2.jpg',
      data:"原创明制立领竖领翻领对襟套装",
      price:"260.00"
    },   
    {
      image_src:'/images/q13.jpg',
      data:"基础款大众旗袍",
      price:"246.00"
    }, 
    {
      image_src:'/images/q17.jpg',
      data:"靛青色夏款马面裙",
      price:"380.00"
    },
    {
      image_src:'/images/q19.jpg',
      data:"明制竖领对襟衫琵琶",
      price:"368.00"
    },   
    {
      image_src:'/images/q21.jpg',
      data:"细葛含风软一",
      price:"246.00"
    }
]
  },
  swichNav: function (e) {
      console.log(e);
      var that = this;
      if (this.data.currentTab === e.target.dataset.current) {
          return false;
      } else {
          that.setData({
              currentTab: e.target.dataset.current,
          })
      }
  },
  swiperChange: function (e) {
      console.log(e);
      this.setData({
          currentTab: e.detail.current,
      })

  },
  onShareAppMessage: function () {
      // 用户点击右上角分享
      return {
          title: 'title', // 分享标题
          desc: 'desc', // 分享描述
          path: 'path' // 分享路径
      }
  }
})


